# Generated by Django 2.2.2 on 2019-06-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20190609_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
            preserve_default=False,
        ),
    ]
