# Generated by Django 2.2.2 on 2019-06-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20190609_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='owner',
            field=models.CharField(default='admin', max_length=200),
            preserve_default=False,
        ),
    ]
